export const GameConfig = {
  // Canvas
  CANVAS_WIDTH: window.innerWidth,
  CANVAS_HEIGHT: window.innerHeight,

  // Player
  INITIAL_SOLDIER_COUNT: 5,
  MAX_SOLDIER_COUNT: 100,
  FORWARD_SPEED: 10,
  HORIZONTAL_SPEED: 15,
  HORIZONTAL_LIMIT: 5,

  // Soldier
  SOLDIER_SIZE: 0.4,
  SOLDIER_HEIGHT: 0.8,
  SOLDIER_SPACING: 0.6,
  SOLDIER_HEALTH: 10,

  // Combat
  FIRE_RATE: 0.2,
  BULLET_SPEED: 50,
  BULLET_DAMAGE: 10,
  BULLET_SIZE: 0.1,
  AUTO_AIM_RANGE: 30,

  // Enemies
  ZOMBIE_HEALTH: 30,
  ZOMBIE_DAMAGE: 5,
  ZOMBIE_SPEED: 3,
  BOSS_HEALTH_MULTIPLIER: 50,
  BOSS_DAMAGE_MULTIPLIER: 3,

  // Gates
  GATE_WIDTH: 3,
  GATE_HEIGHT: 4,
  GATE_DEPTH: 0.5,
  GATE_SPACING: 3,

  // Camera
  CAMERA_HEIGHT: 15,
  CAMERA_DISTANCE: 20,
  CAMERA_FOV: 60,
  CAMERA_LOOK_AHEAD: 10,

  // Mobile/Input
  JOYSTICK_SIZE: 120,
  TOUCH_DEAD_ZONE: 10,

  // Object Pool Sizes
  POOL_BULLETS: 200,
  POOL_SOLDIERS: 100,
  POOL_ENEMIES: 50,

  // Colors
  COLOR_SOLDIER: 0x4a90d9,
  COLOR_ENEMY: 0x8b0000,
  COLOR_BOSS: 0x4a0080,
  COLOR_BULLET: 0xffff00,
  COLOR_GATE_POSITIVE: 0x00ff00,
  COLOR_GATE_NEGATIVE: 0xff0000,
  COLOR_GROUND: 0x2d5a27,
  COLOR_SKY: 0x1a1a2e,

  // Rendering
  MAX_PIXEL_RATIO: 2,
  SHADOW_MAP_SIZE: 1024,
} as const;
